---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-config-slave
data:
  mysqld.cnf: |
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    symbolic-links=0
    server-id       = 2
    relay-log       = /var/log/mysql/mysql-relay-bin.log
    log_bin         = /var/log/mysql/mysql-bin.log
    binlog_do_db    = database_example_test
    general_log     = on
    general_log_file= /var/log/mysql/general.log
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-service-slave
  labels:
    mysql: mysql-slave
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysql-slave"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-service-slave
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector: 
    matchLabels: 
      mysql: mysql-slave
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mysql-service-slave
  labels:
    app: mysql-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "mysqlrootpassword"
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: vol-mysql-service-slave
          - name: config-volume
            mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
            subPath: mysqld.cnf
      volumes:
        - name: vol-mysql-service-slave
          persistentVolumeClaim:
            claimName: pvc-mysql-service-slave
        - name: config-volume
          configMap:
            name: mysql-config-slave
      nodeSelector:
         mysql: slave
---
apiVersion: v1
kind: Service
metadata:
  name: service-mysql-service-slave
spec:
  type: NodePort
  selector:
    app: mysql-slave
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30037